files:
  - source: /main/res/values/strings.xml
    translation: /main/res/values-%two_letters_code%/%original_file_name%
    translate_attributes: 0
    content_segmentation: 0
  - source: /debug/res/values/fdroid.xml
    translation: /debug/res/values-%two_letters_code%/%original_file_name%
    translate_attributes: 0
    content_segmentation: 0
